import { Computer, MaintenanceLog } from './types';

export const SAMPLE_COMPUTERS: Computer[] = [
  {
    id: 'c1',
    assetTag: 'IT-COMP-001',
    serialNumber: 'C02F28GHMD6M',
    makeModel: 'Apple MacBook Pro 14" (M3 Pro, 18GB RAM)',
    os: 'macOS Sonoma 14.5',
    assignedUser: 'Sarah Connor',
    department: 'Engineering',
    location: 'HQ - Floor 4 (Lab A)',
    purchaseDate: '2024-03-12',
    warrantyExpiration: '2027-03-12',
    status: 'Active',
  },
  {
    id: 'c2',
    assetTag: 'IT-COMP-002',
    serialNumber: '5CD3206FX3',
    makeModel: 'HP EliteBook 840 G10 (14" Core i7)',
    os: 'Windows 11 Pro',
    assignedUser: 'Marcus Wright',
    department: 'Operations',
    location: 'HQ - Floor 2 (Cubicle 204)',
    purchaseDate: '2023-08-15',
    warrantyExpiration: '2026-08-15',
    status: 'Active',
  },
  {
    id: 'c3',
    assetTag: 'IT-COMP-003',
    serialNumber: 'PF49G5X8',
    makeModel: 'Lenovo ThinkPad X1 Carbon Gen 11',
    os: 'Windows 11 Pro',
    assignedUser: 'Kate Brewster',
    department: 'Marketing',
    location: 'Remote - New York Office',
    purchaseDate: '2024-01-20',
    warrantyExpiration: '2027-01-20',
    status: 'In Repair',
  },
  {
    id: 'c4',
    assetTag: 'IT-COMP-004',
    serialNumber: 'C02ZL4D2MD6T',
    makeModel: 'Apple MacBook Air 13" (M2, 8GB RAM)',
    os: 'macOS Ventura 13.4',
    assignedUser: 'Kyle Reese',
    department: 'Sales',
    location: 'HQ - Ground Floor Reception',
    purchaseDate: '2022-11-05',
    warrantyExpiration: '2025-11-05', // Warranty Expired!
    status: 'Active',
  },
  {
    id: 'c5',
    assetTag: 'IT-COMP-005',
    serialNumber: '7X8Y9Z1',
    makeModel: 'Dell Precision 5480 Workstation (Ubuntu)',
    os: 'Ubuntu 22.04 LTS',
    assignedUser: 'T-800 Corp Engine',
    department: 'Engineering',
    location: 'HQ - Server Room B',
    purchaseDate: '2025-05-18',
    warrantyExpiration: '2028-05-18',
    status: 'Active',
  },
  {
    id: 'c6',
    assetTag: 'IT-COMP-006',
    serialNumber: 'A4B5C6D',
    makeModel: 'Dell Latitude 5540 Business Laptop',
    os: 'Windows 11 Pro',
    assignedUser: 'Dr. Peter Silberman',
    department: 'Human Resources',
    location: 'HQ - Floor 3 (Office 312)',
    purchaseDate: '2021-06-10',
    warrantyExpiration: '2024-06-10', // Warranty Expired/Retired!
    status: 'Retired',
  }
];

export const SAMPLE_MAINTENANCE_LOGS: MaintenanceLog[] = [
  {
    id: 'm1',
    date: '2025-09-12',
    computerId: 'c3',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Repair',
    description: 'Flickering screen issue. Diagnosed as loose eDP display assembly cable. Disassembled chassis/bezel, reseated connecting pin, tape-reinforced, and benchmarked.',
    partsUsed: 'None',
    timeSpentHours: 1.5,
    cost: 0,
    nextServiceDate: '2026-03-12',
    status: 'Completed',
  },
  {
    id: 'm2',
    date: '2026-01-10',
    computerId: 'c1',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Preventive',
    description: 'Annual wellness check: dust blasting vents/heatsinks, thermal grease replacement (Arctic MX-4), full keyboard wipe-down, sanitization, battery calibration cycle.',
    partsUsed: 'Thermal Paste (Arctic MX-4)',
    timeSpentHours: 1.0,
    cost: 15,
    nextServiceDate: '2027-01-10',
    status: 'Completed',
  },
  {
    id: 'm3',
    date: '2026-03-24',
    computerId: 'c3',
    technicianName: 'John Connor',
    maintenanceType: 'Hardware',
    description: 'Battery diagnosed with cell expanding/bloating causing trackpad deflection. Removed old cells immediately, cleaned compartment, installed genuine factory replacement.',
    partsUsed: 'Lenovo ThinkPad 57Wh Battery Replacement',
    timeSpentHours: 2.0,
    cost: 120,
    nextServiceDate: '2026-09-24',
    status: 'Completed',
  },
  {
    id: 'm4',
    date: '2026-04-05',
    computerId: 'c4',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Software',
    description: 'Standard safe operating system update from older macOS Ventura v13 to macOS Sonoma v14.5. Solved local user profile directory permission conflicts.',
    partsUsed: 'None',
    timeSpentHours: 3.0,
    cost: 0,
    nextServiceDate: '2026-10-05',
    status: 'Completed',
  },
  {
    id: 'm5',
    date: '2026-05-12',
    computerId: 'c2',
    technicianName: 'John Connor',
    maintenanceType: 'Software',
    description: 'Cumulative security package failing install with 0x800f081f errors. Cleared SoftwareDistribution logs, unregistered/reregistered DLLs, verified profile with SFC tool, patched successfully.',
    partsUsed: 'None',
    timeSpentHours: 1.25,
    cost: 0,
    nextServiceDate: '',
    status: 'Completed',
  },
  {
    id: 'm6',
    date: '2026-06-01',
    computerId: 'c5',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Upgrade',
    description: 'Upgraded baseline RAM storage from 16GB pre-install to high-capacity 64GB dual-channel modules to support offline dev containers and telemetry simulators.',
    partsUsed: 'Crucial DDR5 Auto-Calibrated 64GB SO-DIMM Kit',
    timeSpentHours: 0.75,
    cost: 185,
    nextServiceDate: '2026-12-01',
    status: 'Completed',
  },
  {
    id: 'm7',
    date: '2026-06-10',
    computerId: 'c3',
    technicianName: 'John Connor',
    maintenanceType: 'Repair',
    description: 'Minor moisture entry detected at side charge connector ports. System passes hardware safety diagnostics but port current output is unstable. Ordered daughterboard shield.',
    partsUsed: 'Lenovo Yoga/X1 Thunderbolt IO Sub-board',
    timeSpentHours: 0.5,
    cost: 45,
    nextServiceDate: '',
    status: 'In Progress',
  },
  {
    id: 'm8',
    date: '2026-06-12',
    computerId: 'c2',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Hardware',
    description: 'User reported tactile sticky triggers on physical keycap switches CapsLock and Left-Shift. Displaced keyboard, vacuumed switches, replaced keyboard bezel.',
    partsUsed: 'HP EliteBook G10 OEM Keyboard assembly',
    timeSpentHours: 1.5,
    cost: 65,
    nextServiceDate: '',
    status: 'Completed',
  },
  {
    id: 'm9',
    date: '2026-06-14',
    computerId: 'c1',
    technicianName: 'John Connor',
    maintenanceType: 'Upgrade',
    description: 'Cloned default SSD containing 512GB onto newer 2TB NVMe SSD. Expanded standard logical volumes. Excellent read/write transfer rates on benchmark test.',
    partsUsed: 'Crucial T500 PCIe Gen4 M.2 2TB SSD',
    timeSpentHours: 2.5,
    cost: 152,
    nextServiceDate: '2027-06-14',
    status: 'Completed',
  },
  {
    id: 'm10',
    date: '2026-06-15',
    computerId: 'c3',
    technicianName: 'Miles Dyson',
    maintenanceType: 'Repair',
    description: 'Left-side trackpad clicks are reporting inconsistent physical debounce. Undergoing assessment; opening base to check tension adjustments or pressure expansion.',
    partsUsed: 'Pending Diagnostics',
    timeSpentHours: 0.5,
    cost: 0,
    nextServiceDate: '',
    status: 'Open',
  }
];
